### PR TITLE
[ROS-O][GA] build all packages and refactor github action scripts

### PR DESCRIPTION
**Pull request by tongtybj**
### What is this

Some packages cannot be build in GA since there are not explicit dependencies for aerial_robot

### Details

following packages (repositories) were not build in GA:
- livox_ros_driver2
- fast_lio

Actually, these repositories also have the c++ version problem, which has been fixed by 
- https://github.com/tongtybj/livox_ros_driver2/commit/df36045da7b936795d73beb752a6ee987d4ce65d
- https://github.com/tongtybj/FAST_LIO/commit/0681117f927eede2a36e2b6d421a0a5b22fc06f1

### TODO

- [x] check with real platform
- [x] write a script to install ROS-O in 22.04

### CODE REVIEW

**Comment by sugikazu75** [comment]
With https://github.com/tongtybj/livox_ros_driver2/commit/7341ac9bb69fd09fd94e062fd7e8c771d4ec7ed3 and https://github.com/tongtybj/FAST_LIO/commit/0681117f927eede2a36e2b6d421a0a5b22fc06f1 , I could pass te first and second builds on 22.04 image. 
I will check it later with real machine. 
However, the github action fails, which is strange.

**Comment by tongtybj** [comment]
> However, the github action fails, which is strange.

Yes. I am figuring out the problem.
It seems like some dependency problem with PCL: https://github.com/sugikazu75/jsk_aerial_robot/actions/runs/11713695097/job/32626938049?pr=19#step:6:1292

Besides, if we use c++17, the build in ros-melodic env will also fail. This is another problem.

I will fix these problem today.

**Comment by sugikazu75** [comment]
I have checked that `livox_ros_driver2` and `fast_lio` is worked on 22.04 image.

**Comment by sugikazu75** [comment]
@tongtybj  Thank you for your contribution!! CI for all distro is passed. 
I will merge this PR soon, so if you have plan to add more modification, please notify it.

**Comment by tongtybj** [comment]
@sugikazu75 

Thank you for review.
I still have a last commit for this PR, add an instruction for build.

**Review by sugikazu75 — APPROVED** [review]

**Comment by tongtybj** [comment]
@sugikazu75 

I have finished developing. You can merge it

**Comment by sugikazu75** [comment]
Ok. Thank you for your contribution!

**Pull request merged**
